#!/bin/sh

__is_installed(){
	if ! [ -x "$(command -v $1)" ]; then
	  echo "Error: $1 is not installed." >&2
	  exit 1
	fi
}

__check_requirements(){
	# Check if sudo, curl and openvpn are installed
	__is_installed sudo
	__is_installed curl
	__is_installed openvpn
}

__check_requirements

default_dir=${HOME}/.local/scripts/vpnbook_client/
mkdir -p ${default_dir}

echo "Copying Script under ${default_dir}..."
cp vpnbook_wrapper ${default_dir}
chmod 744 ${default_dir}/vpnbook_wrapper
cp vpnbook.config ${default_dir}

cp vpnbook ${default_dir}
chmod 744 ${default_dir}/vpnbook
cp vpnbook_stop ${default_dir}
chmod 744 ${default_dir}/vpnbook_stop
cp password_extractor ${default_dir}
chmod 744 ${default_dir}/password_extractor

echo "In order to work, the User: $USER must be part of a group called vpnstarter. Add the following lines to your sudoers configuration file..."
echo '## Members of the Group vpnstarter can run openvpn'
echo '%vpnstarter ALL=(ALL) PASSWD: /usr/local/sbin/openvpn'
