#!/bin/sh

# Print out the help
__usage(){
    echo "usage: vpnbook_stop [| -h]"
}

__read_property(){
	input="$@"
	if [ ! -f ${config_file} ]; then
		echo "${config_file} does not exist... Aborting..."
		exit 1
	else
		temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
		echo ${temp##*|}
	fi
}

__check_if_up(){
	__wait_for_seconds 10

	local if_id="$@"
	local if_result=$(ifconfig ${if_id} | grep "${if_id}: flags" | cut -d \: -f1)
	if [ "${if_result}" == "${if_id}"  ]; then
		return 1
	else
		return 0
	fi
}
# End functions

vpnbook_if_name=$(__read_property vpnbook_if_name)

# Start Script
while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           __usage
                                exit
                                ;;
        * )                     __usage
                                exit 1
    esac
    shift
done

__check_if_up ${vpnbook_if_name}

# The Tunnel is established if the interface exists
if [ $? -eq 1  ]; then
    ifconfig ${vpnbook_if_name} down
    /etc/rc.d/netif restart
    exit 0;
else
    echo "The provided interface ${vpnbook_if_name} does not exist..."
    exit 1;
fi

